id: AE26DC20E
title: 'Vajrakīla Prayer: A Rain of Accomplishments'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:30:36.047319
  last_modified_at: 2022-02-28 23:30:36.047323
