id: AE26DC20E
title: Prayer to Gyarong Khandro Dechen Wangmo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:30:36.044473
  last_modified_at: 2022-02-28 23:30:36.044479
